export const tracksData = [
  {
    slug: 'support',
    name: 'Support Teams',
    persona: 'support',
    color: '#2196F3',
    icon: 'headset',
    goal: 'Resolve issues faster, reduce escalation, master troubleshooting',
    shortDescription: 'Master Rainbow troubleshooting and support workflows to resolve issues faster and reduce escalation rates.',
    totalDuration: 16,
    moduleCount: 20,
    levels: [
      {
        number: 1,
        name: 'Foundation',
        slug: 'foundation',
        duration: 3,
        modules: [
          { id: 'SUP-101', title: 'Rainbow Platform Overview', duration: 30, contentTypes: ['VID', 'INF', 'QIZ'], primaryType: 'conceptual', objectives: ['Understand Rainbow positioning in the UCaaS market', 'Identify subscription tiers and their key differences', 'Navigate Rainbow client applications'] },
          { id: 'SUP-102', title: 'Navigating the Rainbow Interface', duration: 45, contentTypes: ['VID', 'INT'], primaryType: 'guided', objectives: ['Navigate desktop, web, and mobile clients', 'Locate key features and settings', 'Understand the UX patterns across platforms'] },
          { id: 'SUP-103', title: 'Messaging & Presence Essentials', duration: 30, contentTypes: ['VID', 'INT', 'QIZ'], primaryType: 'guided', objectives: ['Use IM, Bubbles, and file sharing effectively', 'Understand presence states and their meaning', 'Troubleshoot common messaging issues'] },
          { id: 'SUP-104', title: 'Voice & Video Basics', duration: 45, contentTypes: ['VID', 'INT', 'LAB'], primaryType: 'hands-on', objectives: ['Initiate and manage P2P calls', 'Set up and join conferences', 'Use screen sharing in support scenarios'] },
          { id: 'SUP-105', title: 'Support Toolkit Orientation', duration: 30, contentTypes: ['VID', 'REF'], primaryType: 'reference', objectives: ['Navigate the Help Center effectively', 'Use support community resources', 'Understand escalation paths and SLAs'] },
        ],
      },
      {
        number: 2,
        name: 'Practitioner',
        slug: 'practitioner',
        duration: 5,
        modules: [
          { id: 'SUP-201', title: 'Telephony Troubleshooting', duration: 60, contentTypes: ['VID', 'SCN', 'REF'], primaryType: 'scenario', objectives: ['Diagnose PBX overlay issues', 'Troubleshoot softphone connectivity', 'Analyze call quality problems'] },
          { id: 'SUP-202', title: 'Admin Portal for Support', duration: 45, contentTypes: ['INT', 'LAB', 'QIZ'], primaryType: 'hands-on', objectives: ['Navigate the admin portal for support purposes', 'Manage user accounts and settings', 'Access logs and diagnostic information'] },
          { id: 'SUP-203', title: 'Connector Support: CRM Integrations', duration: 60, contentTypes: ['VID', 'SCN', 'REF'], primaryType: 'scenario', objectives: ['Troubleshoot Salesforce connector issues', 'Resolve Zendesk and ServiceNow integration problems', 'Guide customers through connector setup'] },
          { id: 'SUP-204', title: 'Conferencing & Meeting Support', duration: 45, contentTypes: ['VID', 'SCN', 'QIZ'], primaryType: 'scenario', objectives: ['Resolve conference capacity and quality issues', 'Troubleshoot screen sharing problems', 'Support AI meeting features (transcription, bots)'] },
          { id: 'SUP-205', title: 'Network & Connectivity Diagnostics', duration: 45, contentTypes: ['VID', 'LAB', 'REF'], primaryType: 'hands-on', objectives: ['Diagnose WebRTC connectivity issues', 'Identify firewall and proxy conflicts', 'Assess bandwidth requirements'] },
          { id: 'SUP-206', title: 'Mobile Client Support', duration: 30, contentTypes: ['VID', 'SCN', 'REF'], primaryType: 'scenario', objectives: ['Resolve iOS and Android specific issues', 'Troubleshoot push notifications', 'Address battery and performance concerns'] },
        ],
      },
      {
        number: 3,
        name: 'Expert',
        slug: 'expert',
        duration: 5,
        modules: [
          { id: 'SUP-301', title: 'Advanced Telephony: IVR & Call Routing', duration: 60, contentTypes: ['VID', 'LAB', 'QIZ'], primaryType: 'hands-on', objectives: ['Configure and troubleshoot IVR systems', 'Set up hunt groups and call routing', 'Manage open/close calendars'] },
          { id: 'SUP-302', title: 'Deployment Architecture for Support', duration: 45, contentTypes: ['VID', 'INF', 'QIZ'], primaryType: 'conceptual', objectives: ['Understand public cloud vs. Edge vs. hybrid impact on support', 'Identify architecture-specific troubleshooting approaches', 'Navigate deployment documentation'] },
          { id: 'SUP-303', title: 'Security & Compliance Support', duration: 45, contentTypes: ['VID', 'CAS', 'QIZ'], primaryType: 'case-based', objectives: ['Handle encryption and data residency inquiries', 'Address GDPR compliance questions', 'Support security audit preparations'] },
          { id: 'SUP-304', title: 'Teams Connector Troubleshooting', duration: 60, contentTypes: ['VID', 'SCN', 'LAB'], primaryType: 'hands-on', objectives: ['Diagnose Direct Routing issues', 'Resolve coexistence scenario problems', 'Support Teams-Rainbow hybrid environments'] },
          { id: 'SUP-305', title: 'Escalation Mastery & Root Cause Analysis', duration: 45, contentTypes: ['VID', 'SCN', 'CAS'], primaryType: 'scenario', objectives: ['Apply systematic RCA methodology', 'Perform effective log analysis', 'Execute tier-2/3 handoffs with complete context'] },
          { id: 'SUP-306', title: 'Troubleshooting Decision Trees', duration: 45, contentTypes: ['INT'], primaryType: 'interactive', objectives: ['Navigate interactive diagnostic flows', 'Apply decision trees to top 20 support scenarios', 'Build custom troubleshooting workflows'] },
        ],
      },
      {
        number: 4,
        name: 'Champion',
        slug: 'champion',
        duration: 3,
        modules: [
          { id: 'SUP-401', title: 'Support Metrics & KPI Optimization', duration: 60, contentTypes: ['VID', 'CAS', 'QIZ'], primaryType: 'case-based', objectives: ['Track and optimize FCR, MTTR, and escalation rates', 'Correlate support metrics with CSAT', 'Build data-driven support improvement plans'] },
          { id: 'SUP-402', title: 'Knowledge Base Contribution', duration: 45, contentTypes: ['VID', 'LAB'], primaryType: 'hands-on', objectives: ['Write effective knowledge base articles', 'Identify patterns from support cases', 'Build reusable resolution templates'] },
          { id: 'SUP-403', title: 'Mentoring & Team Enablement', duration: 45, contentTypes: ['VID', 'CAS'], primaryType: 'case-based', objectives: ['Train new support team members effectively', 'Create team-specific runbooks', 'Build a culture of continuous improvement'] },
          { id: 'SUP-404', title: 'Certification Assessment', duration: 30, contentTypes: ['ASM'], primaryType: 'assessment', objectives: ['Demonstrate comprehensive Rainbow support expertise', 'Pass the Rainbow Support Champion certification exam'] },
        ],
      },
    ],
  },
  {
    slug: 'customer-success',
    name: 'Customer Success',
    persona: 'customer-success',
    color: '#4CAF50',
    icon: 'trophy',
    goal: 'Drive adoption, demonstrate ROI, maximize customer lifetime value',
    shortDescription: 'Drive customer adoption, articulate business value, and maximize lifetime value through strategic engagement.',
    totalDuration: 17,
    moduleCount: 21,
    levels: [
      {
        number: 1, name: 'Foundation', slug: 'foundation', duration: 3,
        modules: [
          { id: 'CS-101', title: 'Rainbow Value Proposition', duration: 45, contentTypes: ['VID', 'INF', 'CAS'], primaryType: 'strategic', objectives: ['Articulate Rainbow market positioning', 'Identify key differentiators vs. competitors', 'Frame value for different buyer personas'] },
          { id: 'CS-102', title: 'Subscription Tiers & Licensing', duration: 45, contentTypes: ['VID', 'INT', 'REF'], primaryType: 'reference', objectives: ['Explain Essential/Business/Enterprise/Connect/Hub tiers', 'Recommend the right tier per customer profile', 'Navigate the subscription dashboard'] },
          { id: 'CS-103', title: 'Core Features Walk-Through', duration: 45, contentTypes: ['VID', 'INT', 'QIZ'], primaryType: 'guided', objectives: ['Demo messaging, voice/video, conferencing from customer perspective', 'Highlight features that drive adoption', 'Connect features to business outcomes'] },
          { id: 'CS-104', title: 'The Customer Journey with Rainbow', duration: 45, contentTypes: ['VID', 'INF', 'CAS'], primaryType: 'strategic', objectives: ['Map the onboarding-to-expansion lifecycle', 'Identify key milestones and success metrics', 'Recognize churn risk signals early'] },
        ],
      },
      {
        number: 2, name: 'Practitioner', slug: 'practitioner', duration: 5,
        modules: [
          { id: 'CS-201', title: 'Adoption Metrics & Health Scoring', duration: 60, contentTypes: ['VID', 'INT', 'LAB'], primaryType: 'hands-on', objectives: ['Read and interpret usage analytics', 'Build customer health score models', 'Identify early warning signals for churn'] },
          { id: 'CS-202', title: 'Admin Portal Mastery', duration: 45, contentTypes: ['INT', 'LAB', 'QIZ'], primaryType: 'hands-on', objectives: ['Navigate subscription dashboard confidently', 'Manage user provisioning for customers', 'Use directory and settings management'] },
          { id: 'CS-203', title: 'CRM Connector Value Stories', duration: 60, contentTypes: ['VID', 'DEM', 'CAS'], primaryType: 'demo-driven', objectives: ['Demo Salesforce/Dynamics/ServiceNow connectors', 'Quantify time savings from CRM integration', 'Deliver ROI narratives per connector'] },
          { id: 'CS-204', title: 'AI Meeting Features as Value Drivers', duration: 45, contentTypes: ['VID', 'DEM', 'QIZ'], primaryType: 'demo-driven', objectives: ['Demo transcription, action points, meeting bots', 'Quantify productivity gains from AI features', 'Position AI as an adoption accelerator'] },
          { id: 'CS-205', title: 'License Optimization Strategies', duration: 60, contentTypes: ['VID', 'SCN', 'REF'], primaryType: 'scenario', objectives: ['Design mix-and-match license strategies', 'Right-size subscriptions for cost optimization', 'Identify expansion triggers and timing'] },
          { id: 'CS-206', title: 'Conducting Effective Business Reviews', duration: 30, contentTypes: ['VID', 'SCN', 'REF'], primaryType: 'scenario', objectives: ['Structure compelling QBR presentations', 'Use data-driven storytelling techniques', 'Set and track success milestones'] },
        ],
      },
      {
        number: 3, name: 'Expert', slug: 'expert', duration: 6,
        modules: [
          { id: 'CS-301', title: 'Competitive Differentiation Deep Dive', duration: 60, contentTypes: ['VID', 'CAS', 'INF'], primaryType: 'strategic', objectives: ['Compare Rainbow vs. Teams, Zoom, RingCentral, 8x8', 'Handle competitive objections effectively', 'Position Rainbow strengths per customer segment'] },
          { id: 'CS-302', title: 'Deployment Strategy Advisory', duration: 60, contentTypes: ['VID', 'SCN', 'REF'], primaryType: 'scenario', objectives: ['Guide customers through cloud/hybrid/Edge decisions', 'Match deployment model to regulatory requirements', 'Plan phased deployment strategies'] },
          { id: 'CS-303', title: 'Teams Coexistence Storytelling', duration: 45, contentTypes: ['VID', 'DEM', 'CAS'], primaryType: 'strategic', objectives: ['Articulate why Rainbow + Teams > Teams alone', 'Build business cases for coexistence', 'Handle "why not just Teams?" objection'] },
          { id: 'CS-304', title: 'Security & Compliance as Sales Lever', duration: 45, contentTypes: ['VID', 'CAS', 'REF'], primaryType: 'strategic', objectives: ['Present ISO 27001, GDPR, data sovereignty as value', 'Build security-first narratives for executives', 'Compare security posture vs. competitors'] },
          { id: 'CS-305', title: 'Vertical Solution Positioning', duration: 60, contentTypes: ['VID', 'DEM', 'CAS'], primaryType: 'demo-driven', objectives: ['Tailor pitches for hospitality, healthcare, education, gov', 'Use vertical-specific success stories', 'Identify vertical-specific buying triggers'] },
          { id: 'CS-306', title: 'Expansion & Upsell Playbooks', duration: 45, contentTypes: ['VID', 'SCN', 'REF'], primaryType: 'scenario', objectives: ['Execute Essential-to-Enterprise upgrade motions', 'Identify and act on connector upsell triggers', 'Build expansion business cases for stakeholders'] },
          { id: 'CS-307', title: 'Multi-Site & Enterprise Deployment Success', duration: 30, contentTypes: ['VID', 'CAS'], primaryType: 'case-based', objectives: ['Manage complex multi-site accounts', 'Navigate multi-company structures', 'Scale success practices across enterprise customers'] },
        ],
      },
      {
        number: 4, name: 'Champion', slug: 'champion', duration: 3,
        modules: [
          { id: 'CS-401', title: 'Building Customer Success Playbooks', duration: 60, contentTypes: ['VID', 'LAB'], primaryType: 'hands-on', objectives: ['Create reusable CS motion templates', 'Automate common CS workflows', 'Build scalable engagement models'] },
          { id: 'CS-402', title: 'Executive Storytelling & C-Level Engagement', duration: 45, contentTypes: ['VID', 'SCN', 'CAS'], primaryType: 'strategic', objectives: ['Craft board-level ROI narratives', 'Build executive relationship frameworks', 'Present transformation stories with impact metrics'] },
          { id: 'CS-403', title: 'Customer Advocacy & Case Study Development', duration: 45, contentTypes: ['VID', 'CAS'], primaryType: 'case-based', objectives: ['Turn customer success into referenceable stories', 'Build advocacy programs', 'Create compelling case study narratives'] },
          { id: 'CS-404', title: 'Certification Assessment', duration: 30, contentTypes: ['ASM'], primaryType: 'assessment', objectives: ['Demonstrate comprehensive Rainbow CS expertise', 'Pass the Rainbow CS Champion certification exam'] },
        ],
      },
    ],
  },
  {
    slug: 'executives',
    name: 'Executives / CEOs',
    persona: 'executive',
    color: '#9C27B0',
    icon: 'briefcase',
    goal: 'Strategic decision-making, ROI understanding, digital transformation vision',
    shortDescription: 'Gain strategic insight into Rainbow as a digital transformation enabler with clear ROI and competitive advantages.',
    totalDuration: 10,
    moduleCount: 15,
    levels: [
      {
        number: 1, name: 'Foundation', slug: 'foundation', duration: 2,
        modules: [
          { id: 'EXEC-101', title: 'The Rainbow Vision: Why Unified Communications Matter', duration: 30, contentTypes: ['VID', 'INF'], primaryType: 'strategic', objectives: ['Understand UC market trends and digital workplace transformation', 'Recognize the strategic role of unified communications'] },
          { id: 'EXEC-102', title: 'Rainbow Platform at a Glance', duration: 30, contentTypes: ['VID', 'INF', 'REF'], primaryType: 'reference', objectives: ['Overview all platform capabilities in executive summary format', 'Understand the CPaaS + UCaaS combined value'] },
          { id: 'EXEC-103', title: 'Security, Compliance & Data Sovereignty', duration: 30, contentTypes: ['VID', 'INF', 'CAS'], primaryType: 'strategic', objectives: ['Understand certification portfolio (ISO, GDPR, HDS, ANSSI)', 'Evaluate data sovereignty and residency options', 'Assess trust framework vs. competitors'] },
          { id: 'EXEC-104', title: 'Investment Overview: Tiers & ROI', duration: 30, contentTypes: ['VID', 'INF', 'CAS'], primaryType: 'strategic', objectives: ['Understand pricing structure and TCO implications', 'Apply ROI metrics and benchmarks', 'Compare investment vs. alternative solutions'] },
        ],
      },
      {
        number: 2, name: 'Practitioner', slug: 'practitioner', duration: 3,
        modules: [
          { id: 'EXEC-201', title: 'AI-Powered Productivity in Action', duration: 45, contentTypes: ['VID', 'DEM', 'CAS'], primaryType: 'demo-driven', objectives: ['See transcription, meeting bots, and action points in action', 'Quantify AI impact on meeting productivity', 'Understand AI roadmap and future capabilities'] },
          { id: 'EXEC-202', title: 'Deployment Flexibility: Cloud, Edge, Hybrid', duration: 45, contentTypes: ['VID', 'INF', 'SCN'], primaryType: 'strategic', objectives: ['Apply decision framework for deployment model selection', 'Understand regulatory implications per model', 'Plan phased deployment strategies'] },
          { id: 'EXEC-203', title: 'Rainbow + Microsoft Teams: The Coexistence Strategy', duration: 45, contentTypes: ['VID', 'CAS', 'INF'], primaryType: 'strategic', objectives: ['Understand why complement rather than compete', 'Evaluate the business case for Rainbow + Teams', 'Plan coexistence implementation approach'] },
          { id: 'EXEC-204', title: 'Industry-Specific Value', duration: 45, contentTypes: ['VID', 'CAS'], primaryType: 'case-based', objectives: ['Explore vertical solutions for your industry', 'Review industry-specific success stories', 'Identify vertical-specific ROI drivers'] },
        ],
      },
      {
        number: 3, name: 'Expert', slug: 'expert', duration: 3,
        modules: [
          { id: 'EXEC-301', title: 'Digital Transformation Roadmap with Rainbow', duration: 60, contentTypes: ['VID', 'CAS', 'INF'], primaryType: 'strategic', objectives: ['Design phased modernization roadmaps', 'Plan change management strategies', 'Define success metrics and governance'] },
          { id: 'EXEC-302', title: 'Competitive Landscape & Strategic Positioning', duration: 45, contentTypes: ['VID', 'INF', 'CAS'], primaryType: 'strategic', objectives: ['Map Rainbow in the UCaaS/CPaaS competitive landscape', 'Evaluate strategic partnerships and ecosystem', 'Make informed vendor selection decisions'] },
          { id: 'EXEC-303', title: 'PBX Modernization Without Disruption', duration: 45, contentTypes: ['VID', 'CAS', 'INF'], primaryType: 'strategic', objectives: ['Understand PBX overlay investment protection strategy', 'Plan migration paths with minimal business disruption', 'Calculate modernization ROI'] },
          { id: 'EXEC-304', title: 'The CPaaS Opportunity: Custom Communication', duration: 30, contentTypes: ['VID', 'INF'], primaryType: 'conceptual', objectives: ['Understand developer platform as competitive advantage', 'Identify CPaaS use cases for your business', 'Evaluate build vs. buy decisions'] },
        ],
      },
      {
        number: 4, name: 'Champion', slug: 'champion', duration: 2,
        modules: [
          { id: 'EXEC-401', title: 'Building the Business Case for Stakeholders', duration: 45, contentTypes: ['VID', 'REF'], primaryType: 'strategic', objectives: ['Use board presentation templates effectively', 'Build financial models for UC investment', 'Present to C-suite and board with confidence'] },
          { id: 'EXEC-402', title: 'Change Management & Organizational Adoption', duration: 45, contentTypes: ['VID', 'CAS'], primaryType: 'case-based', objectives: ['Design organizational rollout strategies', 'Manage resistance and drive adoption', 'Measure and communicate transformation success'] },
          { id: 'EXEC-403', title: 'Certification Assessment', duration: 30, contentTypes: ['ASM'], primaryType: 'assessment', objectives: ['Demonstrate strategic Rainbow leadership', 'Pass the Rainbow Executive Champion assessment'] },
        ],
      },
    ],
  },
  {
    slug: 'partners',
    name: 'Partners / Resellers',
    persona: 'partner',
    color: '#FF9800',
    icon: 'handshake',
    goal: 'Sell, deploy, and support Rainbow with confidence and business impact',
    shortDescription: 'Build expertise to sell, deploy, and support Rainbow solutions with confidence across all deployment models.',
    totalDuration: 18,
    moduleCount: 20,
    levels: [
      {
        number: 1, name: 'Foundation', slug: 'foundation', duration: 3,
        modules: [
          { id: 'PTR-101', title: 'Rainbow Product Portfolio', duration: 45, contentTypes: ['VID', 'INF', 'REF'], primaryType: 'reference', objectives: ['Master the complete Rainbow product portfolio', 'Understand positioning and target segments', 'Navigate product documentation confidently'] },
          { id: 'PTR-102', title: 'Market Opportunity & Competitive Landscape', duration: 45, contentTypes: ['VID', 'INF', 'CAS'], primaryType: 'strategic', objectives: ['Analyze UCaaS/CPaaS market opportunity', 'Position Rainbow differentiators against competitors', 'Identify target segments and buying triggers'] },
          { id: 'PTR-103', title: 'Subscription Model & Commercial Framework', duration: 45, contentTypes: ['VID', 'REF', 'QIZ'], primaryType: 'reference', objectives: ['Master pricing structure and margin model', 'Navigate deal registration process', 'Structure competitive proposals'] },
          { id: 'PTR-104', title: 'Client Platforms & System Requirements', duration: 30, contentTypes: ['VID', 'REF'], primaryType: 'reference', objectives: ['Specify system requirements for all platforms', 'Understand network prerequisites', 'Plan client deployment strategies'] },
        ],
      },
      {
        number: 2, name: 'Practitioner', slug: 'practitioner', duration: 6,
        modules: [
          { id: 'PTR-201', title: 'PBX Overlay: The Modernization Story', duration: 60, contentTypes: ['VID', 'DEM', 'CAS'], primaryType: 'demo-driven', objectives: ['Articulate PBX overlay business case', 'Demo Rainbow with OXO, OMNI, and third-party PBXs', 'Build modernization proposals'] },
          { id: 'PTR-202', title: 'Deployment Models: Sizing & Recommending', duration: 60, contentTypes: ['VID', 'LAB', 'REF'], primaryType: 'hands-on', objectives: ['Size deployments based on customer requirements', 'Recommend public cloud, Edge, or hybrid', 'Configure deployment environments'] },
          { id: 'PTR-203', title: 'Admin Portal & Provisioning Mastery', duration: 60, contentTypes: ['INT', 'LAB', 'QIZ'], primaryType: 'hands-on', objectives: ['Execute bulk user provisioning', 'Configure company settings and policies', 'Use Rainbow CLI for automation'] },
          { id: 'PTR-204', title: 'Connector Ecosystem: Demo & Sell', duration: 60, contentTypes: ['DEM', 'SCN', 'REF'], primaryType: 'demo-driven', objectives: ['Demo CRM connectors with impact storytelling', 'Position Teams connector as coexistence solution', 'Build connector-led sales motions'] },
          { id: 'PTR-205', title: 'Security & Compliance Selling', duration: 45, contentTypes: ['VID', 'CAS', 'REF'], primaryType: 'strategic', objectives: ['Use certification portfolio as competitive weapon', 'Build trust narratives for regulated industries', 'Navigate security questionnaires confidently'] },
          { id: 'PTR-206', title: 'Vertical Solution Selling', duration: 45, contentTypes: ['VID', 'DEM', 'CAS'], primaryType: 'demo-driven', objectives: ['Tailor pitches for hospitality, healthcare, education, gov', 'Use vertical-specific demos and case studies', 'Build vertical go-to-market strategies'] },
        ],
      },
      {
        number: 3, name: 'Expert', slug: 'expert', duration: 6,
        modules: [
          { id: 'PTR-301', title: 'Advanced Telephony Design', duration: 60, contentTypes: ['VID', 'LAB', 'QIZ'], primaryType: 'hands-on', objectives: ['Design IVR and call routing architectures', 'Configure CTI/Media Bridge for third-party PBX', 'Implement Teams Direct Routing'] },
          { id: 'PTR-302', title: 'Rainbow Edge: Design & Deployment', duration: 60, contentTypes: ['VID', 'LAB', 'REF'], primaryType: 'hands-on', objectives: ['Architect Rainbow Edge private cloud deployments', 'Execute deployment prerequisites and steps', 'Validate and test Edge installations'] },
          { id: 'PTR-303', title: 'Migration Playbooks', duration: 60, contentTypes: ['VID', 'SCN', 'REF'], primaryType: 'scenario', objectives: ['Plan on-prem to cloud migrations', 'Execute legacy PBX to Rainbow transitions', 'Manage hybrid migration phases'] },
          { id: 'PTR-304', title: 'Multi-Site & Enterprise Architecture', duration: 60, contentTypes: ['VID', 'LAB', 'CAS'], primaryType: 'hands-on', objectives: ['Design multi-site deployment architectures', 'Configure multi-company directory federation', 'Manage enterprise-scale deployments'] },
          { id: 'PTR-305', title: 'License Optimization & Deal Structuring', duration: 45, contentTypes: ['VID', 'SCN', 'REF'], primaryType: 'scenario', objectives: ['Design mix-and-match license strategies', 'Structure volume tier deals', 'Build compelling renewal proposals'] },
          { id: 'PTR-306', title: 'CPaaS for Partners: Extending the Offering', duration: 30, contentTypes: ['VID', 'DEM'], primaryType: 'demo-driven', objectives: ['Position API-driven solutions as value-adds', 'Demo IoT and bot capabilities', 'Identify CPaaS opportunities in customer base'] },
        ],
      },
      {
        number: 4, name: 'Champion', slug: 'champion', duration: 3,
        modules: [
          { id: 'PTR-401', title: 'Building a Rainbow Practice', duration: 60, contentTypes: ['VID', 'CAS'], primaryType: 'case-based', objectives: ['Structure team enablement programs', 'Build services wrapping and managed services offerings', 'Create a sustainable Rainbow business'] },
          { id: 'PTR-402', title: 'Pre-Sales Engineering Excellence', duration: 45, contentTypes: ['VID', 'SCN', 'DEM'], primaryType: 'scenario', objectives: ['Execute discovery and needs assessment', 'Design tailored solutions for complex requirements', 'Run effective proof-of-concept engagements'] },
          { id: 'PTR-403', title: 'Customer Success for Partners', duration: 45, contentTypes: ['VID', 'CAS', 'REF'], primaryType: 'case-based', objectives: ['Drive post-sale adoption and value realization', 'Build expansion motions for partner accounts', 'Create renewal and retention strategies'] },
          { id: 'PTR-404', title: 'Certification Assessment', duration: 30, contentTypes: ['ASM'], primaryType: 'assessment', objectives: ['Demonstrate comprehensive Rainbow partner expertise', 'Pass the Rainbow Partner Champion certification exam'] },
        ],
      },
    ],
  },
  {
    slug: 'developers',
    name: 'Developers',
    persona: 'developer',
    color: '#607D8B',
    icon: 'code',
    goal: 'Build, integrate, and extend Rainbow programmatically',
    shortDescription: 'Master Rainbow APIs, SDKs, and developer tools to build custom integrations and extend the platform.',
    totalDuration: 14,
    moduleCount: 17,
    levels: [
      {
        number: 1, name: 'Foundation', slug: 'foundation', duration: 2,
        modules: [
          { id: 'DEV-101', title: 'Rainbow CPaaS: Platform & Architecture', duration: 30, contentTypes: ['VID', 'INF', 'REF'], primaryType: 'conceptual', objectives: ['Understand Rainbow CPaaS architecture', 'Overview REST API, SDKs, webhooks, S2S', 'Identify integration patterns'] },
          { id: 'DEV-102', title: 'Developer Environment Setup', duration: 30, contentTypes: ['VID', 'LAB'], primaryType: 'hands-on', objectives: ['Register on the developer hub', 'Generate API keys and sandbox configuration', 'Set up local development environment'] },
          { id: 'DEV-103', title: 'Your First Rainbow Application', duration: 30, contentTypes: ['LAB', 'QIZ'], primaryType: 'hands-on', objectives: ['Connect and authenticate with Rainbow API', 'Send and receive messages programmatically', 'Handle real-time events'] },
          { id: 'DEV-104', title: 'Authentication & Security Model', duration: 30, contentTypes: ['VID', 'LAB', 'REF'], primaryType: 'hands-on', objectives: ['Implement OAuth and token management', 'Understand app tokens vs. user tokens', 'Apply security best practices'] },
        ],
      },
      {
        number: 2, name: 'Practitioner', slug: 'practitioner', duration: 5,
        modules: [
          { id: 'DEV-201', title: 'REST API Deep Dive', duration: 60, contentTypes: ['VID', 'LAB', 'REF'], primaryType: 'hands-on', objectives: ['Master core endpoints: contacts, bubbles, messages, presence', 'Handle pagination, filtering, and error responses', 'Build CRUD operations for Rainbow resources'] },
          { id: 'DEV-202', title: 'Web SDK: Building Browser Apps', duration: 60, contentTypes: ['VID', 'LAB', 'QIZ'], primaryType: 'hands-on', objectives: ['Build real-time messaging in the browser', 'Implement audio/video calls with Web SDK', 'Handle connection lifecycle and events'] },
          { id: 'DEV-203', title: 'Node.js SDK: Backend Automation', duration: 60, contentTypes: ['VID', 'LAB', 'QIZ'], primaryType: 'hands-on', objectives: ['Build server-side Rainbow bots', 'Implement event-driven automation', 'Process and transform Rainbow data'] },
          { id: 'DEV-204', title: 'S2S API & Webhooks', duration: 45, contentTypes: ['VID', 'LAB'], primaryType: 'hands-on', objectives: ['Set up server-to-server architecture', 'Configure and validate webhook callbacks', 'Build event-driven backend services'] },
          { id: 'DEV-205', title: 'Building Chatbots', duration: 45, contentTypes: ['VID', 'LAB', 'QIZ'], primaryType: 'hands-on', objectives: ['Create bots with Rainbow-Chatbot framework', 'Design JSON-based conversation scenarios', 'Integrate NLP services (IBM Watson)'] },
        ],
      },
      {
        number: 3, name: 'Expert', slug: 'expert', duration: 5,
        modules: [
          { id: 'DEV-301', title: 'Telephony APIs & CTI Integration', duration: 60, contentTypes: ['VID', 'LAB'], primaryType: 'hands-on', objectives: ['Implement programmatic call control', 'Build IVR scripts via API', 'Integrate with PBX bridge programmatically'] },
          { id: 'DEV-302', title: 'IoT Integration Patterns', duration: 60, contentTypes: ['VID', 'LAB', 'CAS'], primaryType: 'hands-on', objectives: ['Connect IoT devices to Rainbow bots', 'Build monitoring and alerting systems', 'Design smart building communication workflows'] },
          { id: 'DEV-303', title: 'Mobile SDKs (iOS & Android)', duration: 60, contentTypes: ['VID', 'LAB'], primaryType: 'hands-on', objectives: ['Embed Rainbow in native mobile apps', 'Handle push notifications and media', 'Optimize for mobile performance'] },
          { id: 'DEV-304', title: 'C# SDK: Enterprise Windows Integration', duration: 45, contentTypes: ['VID', 'LAB'], primaryType: 'hands-on', objectives: ['Build .NET integrations with Rainbow', 'Embed Rainbow in desktop Windows applications', 'Use C# SDK for enterprise scenarios'] },
          { id: 'DEV-305', title: 'Rainbow CLI & Admin Automation', duration: 45, contentTypes: ['VID', 'LAB', 'REF'], primaryType: 'hands-on', objectives: ['Script provisioning and administration tasks', 'Automate bulk operations via CLI', 'Integrate Rainbow admin into CI/CD pipelines'] },
        ],
      },
      {
        number: 4, name: 'Champion', slug: 'champion', duration: 2,
        modules: [
          { id: 'DEV-401', title: 'Architecture Best Practices & Scalability', duration: 45, contentTypes: ['VID', 'CAS', 'REF'], primaryType: 'case-based', objectives: ['Apply production-ready architecture patterns', 'Handle rate limits and error recovery', 'Design for scalability and resilience'] },
          { id: 'DEV-402', title: 'Contributing to the Ecosystem', duration: 30, contentTypes: ['VID'], primaryType: 'conceptual', objectives: ['Publish to the Rainbow marketplace', 'Contribute to open-source Rainbow projects', 'Engage with the developer community'] },
          { id: 'DEV-403', title: 'Certification Assessment', duration: 30, contentTypes: ['ASM'], primaryType: 'assessment', objectives: ['Demonstrate comprehensive Rainbow development expertise', 'Pass the Rainbow Developer Champion certification exam'] },
        ],
      },
    ],
  },
  {
    slug: 'sales',
    name: 'Sales Professionals',
    persona: 'sales',
    color: '#E91E63',
    icon: 'target',
    goal: 'Position Rainbow with confidence, deliver compelling demos, and close deals',
    shortDescription: 'Master Rainbow positioning, competitive differentiation, demo delivery, and deal closing strategies for direct sales success.',
    totalDuration: 15,
    moduleCount: 18,
    levels: [
      {
        number: 1, name: 'Foundation', slug: 'foundation', duration: 3,
        modules: [
          { id: 'SLS-101', title: 'Rainbow Market Position & Value Proposition', duration: 45, contentTypes: ['VID', 'INF', 'QIZ'], primaryType: 'conceptual', objectives: ['Articulate Rainbow positioning in the UCaaS/CPaaS market', 'Explain the ALE heritage and hybrid cloud differentiators', 'Identify the 5 subscription tiers and ideal customer profiles', 'Position data sovereignty as a unique selling point'] },
          { id: 'SLS-102', title: 'Know Your Buyer: Personas & Pain Points', duration: 45, contentTypes: ['VID', 'CAS', 'QIZ'], primaryType: 'case-based', objectives: ['Map the typical buying committee roles and motivations', 'Identify top pain points for IT directors, CIOs, and LOB owners', 'Match Rainbow capabilities to specific buyer pain points', 'Recognize buying signals and readiness indicators'] },
          { id: 'SLS-103', title: 'Rainbow Product Walkthrough for Sales', duration: 45, contentTypes: ['VID', 'DEM', 'INT'], primaryType: 'demo-driven', objectives: ['Navigate desktop, web, and mobile clients confidently', 'Demonstrate messaging, Bubbles, voice/video, and conferencing', 'Highlight AI features as differentiators', 'Present the admin portal from an ease-of-management perspective'] },
          { id: 'SLS-104', title: 'Subscription Tiers, Pricing & Deal Mechanics', duration: 30, contentTypes: ['VID', 'REF', 'QIZ'], primaryType: 'reference', objectives: ['Explain pricing and feature sets for all tiers', 'Describe the mix-and-match licensing model', 'Navigate deal registration and quoting processes', 'Identify upsell paths from entry to enterprise'] },
        ],
      },
      {
        number: 2, name: 'Practitioner', slug: 'practitioner', duration: 5,
        modules: [
          { id: 'SLS-201', title: 'Competitive Battlecards in Action', duration: 60, contentTypes: ['VID', 'SCN', 'REF'], primaryType: 'scenario', objectives: ['Counter Microsoft Teams, Zoom, RingCentral, and 8x8 objections', 'Execute the "why not just Teams?" handling framework', 'Position Rainbow + Teams coexistence as strategic advantage', 'Adapt competitive messaging for different verticals'] },
          { id: 'SLS-202', title: 'The Rainbow Demo That Sells', duration: 60, contentTypes: ['DEM', 'SCN', 'LAB'], primaryType: 'demo-driven', objectives: ['Deliver a structured 20-minute discovery-based demo', 'Customize demo flow based on prospect pain points', 'Demonstrate CRM connectors with business impact storytelling', 'Handle live objections during demo without losing momentum'] },
          { id: 'SLS-203', title: 'PBX Overlay: Selling Modernization Without Disruption', duration: 45, contentTypes: ['VID', 'DEM', 'CAS'], primaryType: 'demo-driven', objectives: ['Explain PBX overlay value for OmniPCX and third-party PBX prospects', 'Position Rainbow as investment protection not rip-and-replace', 'Build a phased modernization narrative that reduces risk', 'Reference case studies of successful PBX overlay deployments'] },
          { id: 'SLS-204', title: 'Security, Compliance & Data Sovereignty as Deal Winners', duration: 45, contentTypes: ['VID', 'CAS', 'REF'], primaryType: 'case-based', objectives: ['Present ISO 27001, HDS, and GDPR certifications confidently', 'Position 22 data centers and sovereignty as deal-winning differentiators', 'Navigate security questionnaires and RFP security sections', 'Sell to regulated industries using compliance as a lever'] },
          { id: 'SLS-205', title: 'Discovery, Qualification & Pipeline Management', duration: 60, contentTypes: ['VID', 'SCN', 'QIZ'], primaryType: 'scenario', objectives: ['Execute structured discovery using MEDDIC adapted for Rainbow', 'Qualify opportunities based on deployment readiness and PBX landscape', 'Build a value-driven pipeline with accurate deal stages', 'Identify and engage economic buyers vs. technical evaluators'] },
        ],
      },
      {
        number: 3, name: 'Expert', slug: 'expert', duration: 5,
        modules: [
          { id: 'SLS-301', title: 'Vertical Selling: Tailored Pitches by Industry', duration: 60, contentTypes: ['VID', 'DEM', 'CAS'], primaryType: 'demo-driven', objectives: ['Deliver industry-specific demos for hospitality, healthcare, education, and government', 'Use vertical case studies and ROI data', 'Address industry-specific compliance requirements', 'Identify vertical buying cycles and triggers'] },
          { id: 'SLS-302', title: 'Enterprise & Multi-Site Deal Strategy', duration: 60, contentTypes: ['VID', 'SCN', 'CAS'], primaryType: 'scenario', objectives: ['Navigate complex enterprise sales cycles with multiple stakeholders', 'Design multi-site deployment proposals with phased rollouts', 'Structure volume licensing with mix-and-match tier strategies', 'Build executive-level business cases with TCO and ROI models'] },
          { id: 'SLS-303', title: 'CPaaS & Developer Platform Selling', duration: 45, contentTypes: ['VID', 'DEM', 'INF'], primaryType: 'demo-driven', objectives: ['Position Rainbow Hub as a revenue-generating integration platform', 'Demonstrate API capabilities and webhook automation to technical buyers', 'Identify CPaaS use cases that unlock new budget', 'Differentiate Rainbow CPaaS from Twilio and Vonage'] },
          { id: 'SLS-304', title: 'AI Features as Deal Accelerators', duration: 45, contentTypes: ['VID', 'DEM', 'CAS'], primaryType: 'demo-driven', objectives: ['Demo transcription, meeting summaries, and real-time translation', 'Quantify AI-driven ROI for prospects', 'Position AI roadmap as a reason to buy now', 'Handle "we can get AI from Microsoft" objections'] },
          { id: 'SLS-305', title: 'Negotiation & Closing Techniques for Rainbow Deals', duration: 60, contentTypes: ['VID', 'SCN', 'QIZ'], primaryType: 'scenario', objectives: ['Apply negotiation frameworks to Rainbow deal situations', 'Handle pricing objections and defend value over discounts', 'Structure proposals that accelerate procurement review', 'Execute closing plays for different deal types'] },
        ],
      },
      {
        number: 4, name: 'Champion', slug: 'champion', duration: 3,
        modules: [
          { id: 'SLS-401', title: 'Building Repeatable Sales Plays', duration: 60, contentTypes: ['VID', 'CAS', 'LAB'], primaryType: 'case-based', objectives: ['Design sales plays for top 5 deal scenarios', 'Create reusable discovery templates and demo scripts', 'Build a personal playbook of winning deal patterns', 'Coach junior sales reps using play-based methodology'] },
          { id: 'SLS-402', title: 'Executive Engagement & C-Level Selling', duration: 45, contentTypes: ['VID', 'SCN', 'CAS'], primaryType: 'scenario', objectives: ['Craft board-level ROI narratives with financial modeling', 'Build and maintain executive relationships beyond initial sale', 'Present digital transformation vision to CIOs and CFOs', 'Navigate executive objections about vendor consolidation'] },
          { id: 'SLS-403', title: 'Account Strategy & Customer Expansion', duration: 45, contentTypes: ['VID', 'SCN', 'REF'], primaryType: 'scenario', objectives: ['Design land-and-expand strategies for named accounts', 'Identify expansion triggers from usage patterns', 'Build multi-year account plans with growth targets', 'Transition accounts smoothly from sales to customer success'] },
          { id: 'SLS-404', title: 'Certification Assessment', duration: 30, contentTypes: ['ASM'], primaryType: 'assessment', objectives: ['Demonstrate comprehensive Rainbow sales expertise', 'Pass the Rainbow Sales Champion certification exam'] },
        ],
      },
    ],
  },
  {
    slug: 'administrators',
    name: 'Rainbow Administrators',
    persona: 'administrator',
    color: '#00897B',
    icon: 'settings',
    goal: 'Configure, manage, and optimize Rainbow for your organization',
    shortDescription: 'Master the Rainbow admin portal to provision users, configure telephony, manage security, and optimize your deployment.',
    totalDuration: 15,
    moduleCount: 18,
    levels: [
      {
        number: 1, name: 'Foundation', slug: 'foundation', duration: 3,
        modules: [
          { id: 'ADM-101', title: 'Rainbow Admin Portal Overview', duration: 45, contentTypes: ['VID', 'INT', 'QIZ'], primaryType: 'guided', objectives: ['Navigate the admin portal dashboard and key configuration areas', 'Understand the relationship between company, users, and subscriptions', 'Identify admin roles and permission levels', 'Locate system status, notifications, and support resources'] },
          { id: 'ADM-102', title: 'Company Setup & Organization Structure', duration: 30, contentTypes: ['VID', 'INT', 'REF'], primaryType: 'guided', objectives: ['Configure company profile, branding, and contact information', 'Set up multi-site structures and site hierarchies', 'Define organizational units and departments', 'Configure company-wide default settings and policies'] },
          { id: 'ADM-103', title: 'User Provisioning & License Assignment', duration: 45, contentTypes: ['VID', 'LAB', 'QIZ'], primaryType: 'hands-on', objectives: ['Create individual user accounts with appropriate profiles', 'Perform bulk user provisioning via CSV import', 'Assign and manage subscription licenses per user', 'Configure user settings: caller ID, voicemail, device associations'] },
          { id: 'ADM-104', title: 'Understanding Rainbow Architecture', duration: 30, contentTypes: ['VID', 'INF', 'REF'], primaryType: 'conceptual', objectives: ['Understand public cloud, Edge, and hybrid deployment models', 'Identify which configuration options depend on deployment model', 'Map the relationship between Rainbow cloud and on-premises PBX', 'Understand data flow, client connectivity, and service dependencies'] },
        ],
      },
      {
        number: 2, name: 'Practitioner', slug: 'practitioner', duration: 5,
        modules: [
          { id: 'ADM-201', title: 'Telephony Configuration & PBX Integration', duration: 60, contentTypes: ['VID', 'LAB', 'QIZ'], primaryType: 'hands-on', objectives: ['Configure SIP trunking and PSTN connectivity settings', 'Set up Rainbow PBX overlay with OmniPCX Enterprise or Office', 'Configure hunt groups, IVR menus, and call routing rules', 'Manage DDI number assignments and call forwarding'] },
          { id: 'ADM-202', title: 'Directory Management & Federation', duration: 45, contentTypes: ['VID', 'LAB', 'QIZ'], primaryType: 'hands-on', objectives: ['Configure LDAP/Active Directory synchronization', 'Manage external contacts and shared company directories', 'Set up federation rules for inter-company communication', 'Troubleshoot directory sync failures and duplicate resolution'] },
          { id: 'ADM-203', title: 'Security Policies & Access Control', duration: 60, contentTypes: ['VID', 'LAB', 'REF'], primaryType: 'hands-on', objectives: ['Configure password policies, session timeouts, and MFA', 'Set up IP restriction rules and geo-blocking policies', 'Define data retention and content archiving rules', 'Configure SSO integration (SAML 2.0 / OpenID Connect)'] },
          { id: 'ADM-204', title: 'Connector Administration', duration: 45, contentTypes: ['VID', 'LAB', 'SCN'], primaryType: 'hands-on', objectives: ['Install and configure CRM connectors for Salesforce and Dynamics', 'Set up the Microsoft Teams connector and coexistence policies', 'Configure connector permissions, user mappings, and sync', 'Troubleshoot common connector authentication and sync issues'] },
          { id: 'ADM-205', title: 'Monitoring, Logs & Usage Analytics', duration: 60, contentTypes: ['VID', 'INT', 'LAB'], primaryType: 'hands-on', objectives: ['Navigate the admin analytics dashboard for call quality metrics', 'Access and interpret system logs for troubleshooting', 'Generate usage reports for license optimization', 'Set up alerts and notifications for system health events'] },
        ],
      },
      {
        number: 3, name: 'Expert', slug: 'expert', duration: 5,
        modules: [
          { id: 'ADM-301', title: 'Advanced Telephony: IVR Design & Call Flows', duration: 60, contentTypes: ['VID', 'LAB', 'SCN'], primaryType: 'hands-on', objectives: ['Design multi-level IVR trees with conditional routing', 'Configure open/close calendars and holiday schedules', 'Set up call recording policies and compliance rules', 'Implement call queue management with overflow and failover'] },
          { id: 'ADM-302', title: 'Rainbow Edge & Hybrid Administration', duration: 60, contentTypes: ['VID', 'LAB', 'REF'], primaryType: 'hands-on', objectives: ['Manage Rainbow Edge server configuration and updates', 'Monitor Edge server health and certificate management', 'Configure hybrid cloud/on-premises service distribution', 'Execute disaster recovery and service failover testing'] },
          { id: 'ADM-303', title: 'Compliance, Data Sovereignty & Audit Readiness', duration: 45, contentTypes: ['VID', 'CAS', 'REF'], primaryType: 'case-based', objectives: ['Configure data residency settings for GDPR and HDS compliance', 'Prepare for IT security audits with Rainbow documentation', 'Manage data export requests and right-to-erasure workflows', 'Configure content retention and legal hold policies'] },
          { id: 'ADM-304', title: 'Bulk Operations & CLI Automation', duration: 60, contentTypes: ['VID', 'LAB', 'QIZ'], primaryType: 'hands-on', objectives: ['Use Rainbow CLI for scripted bulk user operations', 'Automate recurring admin tasks using scheduled scripts', 'Build provisioning workflows for onboarding and offboarding', 'Integrate Rainbow admin operations with ITSM tools'] },
          { id: 'ADM-305', title: 'Network Requirements & Quality of Service', duration: 45, contentTypes: ['VID', 'SCN', 'REF'], primaryType: 'scenario', objectives: ['Define and validate network requirements for Rainbow', 'Configure QoS policies for voice/video priority', 'Diagnose call quality issues using MOS, jitter, and packet loss', 'Plan network changes for Rainbow rollout to new sites'] },
        ],
      },
      {
        number: 4, name: 'Champion', slug: 'champion', duration: 4,
        modules: [
          { id: 'ADM-401', title: 'Multi-Site & Enterprise-Scale Administration', duration: 60, contentTypes: ['VID', 'CAS', 'SCN'], primaryType: 'case-based', objectives: ['Design admin delegation models for multi-site organizations', 'Manage multi-company structures with shared services', 'Plan and execute site-by-site rollouts with staged configs', 'Build operational runbooks for large-scale administration'] },
          { id: 'ADM-402', title: 'Adoption, Change Management & End-User Enablement', duration: 45, contentTypes: ['VID', 'CAS', 'REF'], primaryType: 'case-based', objectives: ['Design end-user training and communication plans', 'Monitor adoption metrics and identify low-engagement departments', 'Create self-service help resources and internal FAQs', 'Manage change from pilot to full deployment'] },
          { id: 'ADM-403', title: 'Capacity Planning, Optimization & Lifecycle Management', duration: 45, contentTypes: ['VID', 'SCN', 'REF'], primaryType: 'scenario', objectives: ['Analyze usage trends to forecast license and capacity needs', 'Optimize license allocation by matching tier to user behavior', 'Plan Rainbow version upgrades and feature rollouts', 'Build an annual admin operations calendar'] },
          { id: 'ADM-404', title: 'Certification Assessment', duration: 30, contentTypes: ['ASM'], primaryType: 'assessment', objectives: ['Demonstrate comprehensive Rainbow administration expertise', 'Pass the Rainbow Administrator Champion certification exam'] },
        ],
      },
    ],
  },
]
